"""empty message

Revision ID: 5e3a3bce40b5
Revises: ffdc0a98111c
Create Date: 2021-06-30 17:04:35.679814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3a3bce40b5'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('course_api', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tee_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('course_api', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_users',
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('teeTimeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teeTimeId'], ['tee_times.id'], )
    )
    op.add_column('users', sa.Column('first_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('play_level', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('profile_pic', sa.String(length=500), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'play_level')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_table('booked_users')
    op.drop_table('tee_times')
    op.drop_table('reviews')
    # ### end Alembic commands ###
