"""empty message

Revision ID: d822ee72ae29
Revises: 74c392f4b1dd
Create Date: 2021-07-11 01:57:07.834909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd822ee72ae29'
down_revision = '74c392f4b1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('names', sa.String(length=50), nullable=True))
    op.add_column('tee_times', sa.Column('time', sa.String(40), nullable=True))
    op.add_column('tee_times', sa.Column('date', sa.String(40), nullable=True))
    # op.alter_column('tee_times', 'date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tee_times', 'date',
    #            existing_type=postgresql.TIMESTAMP(),
    #            nullable=True)
    op.drop_column('reviews', 'names')
    # ### end Alembic commands ###
