"""empty message

Revision ID: 74c392f4b1dd
Revises: 5e3a3bce40b5
Create Date: 2021-07-09 10:29:35.562347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c392f4b1dd'
down_revision = '5e3a3bce40b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tee_times', sa.Column('time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tee_times', 'time')
    # ### end Alembic commands ###
