"""empty message

Revision ID: 3aea38f105b1
Revises: 
Create Date: 2021-07-12 04:05:16.756032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aea38f105b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('play_level', sa.String(length=20), nullable=False),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('course_api', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tee_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=False),
    sa.Column('time', sa.String(length=40), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('course_api', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_users',
    sa.Column('playerId', sa.Integer(), nullable=True),
    sa.Column('teeTimeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teeTimeId'], ['tee_times.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booked_users')
    op.drop_table('tee_times')
    op.drop_table('reviews')
    op.drop_table('users')
    # ### end Alembic commands ###
